name: Deploy Next.js to AWS EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Verify Build Output
        run: ls -la .next  # Must show files here

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjsbuild
          path: .next/
          retention-days: 1  # Optional: Reduce retention time for testing

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjsbuild
          path: build-artifact

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            echo "Deploying build..."
            cd /var/www/nextjs-app
            rm -rf .next
            cp -R build-artifact/.next ./
            npm install --production
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
